apps/examplePurchases/urls.py
from django.urls import path
from . import views

app_name = 'examplePurchases'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create/', views.Create.as_view(), name='create'),
    path('show/<int:pk>/', views.Show.as_view(), name='show'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
    path('deleteRelation/<int:pk>', views.DeleteRelation.as_view(), name='deleteRelation'),
]

djangoproject/urls.py
"""djangoproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.urls import include, path
from apps.users import views as users_views
from django.contrib.admin.views.decorators import staff_member_required


# from exampleApp.views import IndexExample

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('apps.dashboard.urls')),
    path('inventario/', include('apps.exampleInventario.urls')),
    path('compras/', include('apps.examplePurchases.urls')),
    path('log/', include('apps.history.urls')),
    path('animals/', include('apps.drfexampleapp.urls')),
    
    # User and Registration urls
    path('', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('profile/', users_views.ProfileView.as_view(), name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/login.html'), name='logout'),
    path('register/', users_views.RegisterView.as_view(), name='register'),
    path('register-admin/', staff_member_required(users_views.RegisterViewAdmin.as_view()), name='registerAdmin'),

    path('forgot-password/', users_views.forgot_password, name='forgot-password'),
    path('users/', include('apps.users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Remember that the last line regarding file/image uploads must be changed for production purposes: 
# https://docs.djangoproject.com/en/4.0/howto/static-files/deployment/

apps/examplePurchases/models.py
from datetime import datetime
from django.db import models
from simple_history.models import HistoricalRecords
from safedelete.models import SafeDeleteModel, SOFT_DELETE_CASCADE

class Purchase(SafeDeleteModel):
    _safedelete_policy = SOFT_DELETE_CASCADE
    total_price = models.CharField(max_length=255)
    description = models.CharField(max_length=65535)
    date = models.DateField(default=datetime.now)
    history = HistoricalRecords()
    
    class Meta:
        verbose_name = "Purchase"    
        verbose_name_plural = "Purchases"
        db_table = "purchase"
        ordering = ['-id']      # Orders by Id ("-" means descending)



class InventoryPurchase(SafeDeleteModel):
    _safedelete_policy = SOFT_DELETE_CASCADE
    inventory = models.ForeignKey('exampleInventario.Inventario', on_delete = models.CASCADE)
    purchase = models.ForeignKey(Purchase, on_delete = models.CASCADE)
    price = models.CharField(max_length=10)
    supplier = models.CharField(max_length=255)
    quantity = models.CharField(max_length=255)
    transaction_type = models.CharField(max_length=255, default='entry')
    history = HistoricalRecords()

    class Meta:
        verbose_name = "InventoryPurchase"    
        verbose_name_plural = "InventoryPurchases"
        db_table = "inventory_purchases"
        ordering = ['-id']      # Orders by Id ("-" means descending)


apps/examplePurchases/forms.py
from .models import Purchase
from django import forms

class PurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = '__all__' # You can change this for the field's name
        exclude = ['is_deleted' , 'deleted_at']
        
        labels = {
            'description': ('Descripción'),
            'product_count': ('Número de productos'),
            'total_price': (''),
            'date': ('Fecha'),
        }
        widgets = {
            'description': forms.TextInput(attrs={'placeholder':'Descripción de la compra'}),
            'product_count': forms.NumberInput(attrs={'placeholder':'0', 'value':'0', 'id':'product_count', 'min':'0'}),
            'total_price': forms.NumberInput(attrs={'placeholder':'0', 'value':'0'}),
            'date': forms.DateInput(attrs={'type':'date'}),
        }

apps/examplePurchases/views.py
from django.views.generic.list import ListView
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from django_filters.views import FilterView
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect, render
from django.db import transaction
from django.core.exceptions import ValidationError

from ..exampleInventario.models import Inventario
from .forms import PurchaseForm, Purchase
from .models import InventoryPurchase
from .filters import PurchaseFilter


# Index
class Index(FilterView):
    model = Purchase
    template_name = "examplePurchases/index.html"
    context_object_name = 'purchases'
    paginate_by = 20
    filterset_class = PurchaseFilter


# Create
class Create(CreateView):
    model = Purchase
    template_name = "examplePurchases/create.html"
    form_class = PurchaseForm
    success_url = reverse_lazy('examplePurchases:index')
    
    # Override the context that is passed to the template.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['inventario'] = Inventario.objects.all()
        return context
    
    def form_invalid(self, form):
        return super(CreateView, self).form_invalid(form)

    # Override the save method that Django uses to store the form's POST data.
    @transaction.atomic
    def post(self, request):

        # Get the Purchase's Form data sent through the POST
        form = PurchaseForm(request.POST)


        # Check if the data in our form is valid before saving the data
        if form.is_valid():
        
            # save current point of database
            sid = transaction.savepoint()

            # Create the purchase and save it in a variable for later use as a ForeignKey
            purchase = form.save()



            # Loop through the POST data to get the id of each N item in a dict of our own
            product_keys = {}
            product_count = 0
            for key in request.POST :
                # If input name matches, we store the id as a value in our dict
                if key.find("product_name_") != -1:
                    product_keys[product_count] = key.split("_")[2]
                    product_count += 1

            # Now we iterate our dictionary with the ID values to get each form field sent
            for id in product_keys.values():

                if request.POST.get('product_name_' + str(id)) is None:
                    break

                product = request.POST.__getitem__('product_name_' + str(id))
                quantity = request.POST.__getitem__('quantity_' + str(id))
                price = request.POST.__getitem__('price_' + str(id))

                # CHECK IF THE PRODUCT NAME IS A NUMBER IF IT IS A NUMBER, THEN IT IS A PRODUCT ID
                if product.isdigit():
                    # Link the product to the current Purchase
                    InventoryPurchase.objects.create(
                        inventory = Inventario.objects.get(id=product),
                        purchase = purchase,
                        price = price,
                        supplier = "",
                        quantity = quantity,
                        transaction_type = "storage",
                    )
                # IF IT IS NOT A NUMBER, THEN IT IS A PRODUCT NAME AND WE NEED TO CREATE A NEW PRODUCT
                else:
                    inventory_name = product

                    # Try to get the product with the same SKU
                    if Inventario.objects.filter(sku=request.POST.__getitem__('sku_' + str(id))).exists():
                    # If the product exists it return a error
                        msg = "One SKU already exits. Please enter a different SKU"
                        form.add_error(None, msg)

                        # send error messages in context
                        context = {'form': form}
                        context['inventario'] = Inventario.objects.all()

                        # Rollback the database to the previous state
                        transaction.savepoint_rollback(sid)

                        # Return the form with the error message
                        return render(request, self.template_name, context)


                    #If not exist continue with the creation of the product
                    inventory = Inventario.objects.create(
                        nombre = inventory_name,
                        sku = request.POST.__getitem__('sku_' + str(id))
                    )

                    # Link the product to the current Purchase
                    InventoryPurchase.objects.create(
                        inventory = inventory,
                        purchase = purchase,
                        price = price,
                        supplier = "",
                        quantity = quantity,
                        transaction_type = "storage",
                    )
            # If everything is ok, commit the changes to the database
            transaction.savepoint_commit(sid)
            
            return redirect(self.success_url)
        
        else:
            context = {'form': form}
            return render(request, self.template_name, context)


# Show
class Show(DetailView):
    model = Purchase
    template_name = "examplePurchases/showPurchase.html"
    context_object_name = 'purchase'

    # Override the context that is passed to the template.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get the current id of the puchase
        id_purchase = self.kwargs['pk']

        # With filter we will get the products related to our current purchase 
        # NOTE: to acces the inventory fields we must first access the model's foreign key (in the template)
        context['inventario'] = InventoryPurchase.objects.filter(purchase_id = id_purchase)
        return context


# Edit
class Edit(UpdateView):
    model = Purchase
    template_name = "examplePurchases/edit.html"
    form_class = PurchaseForm
    success_url = reverse_lazy('examplePurchases:index')

    # Override the context that is passed to the template.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get the current id of the puchase
        id_purchase = self.kwargs['pk']

        # With filter we will get the products related to our current purchase 
        # NOTE: to access the inventory fields we must first access the model's foreign key (in the template)
        context['inventario'] = InventoryPurchase.objects.filter(purchase_id = id_purchase)
        context['all_products'] = Inventario.objects.all()
        return context
        

    # Override the save method that Django uses to store the form's POST data.
    @transaction.atomic
    def post(self, request, *args, **kwargs):

        # Get the Purchase's Form data sent through the POST
        form = PurchaseForm(request.POST, instance = self.get_object())

        # Check if the data in our form is valid before saving the data
        if form.is_valid():

            # save current point of database
            sid = transaction.savepoint()

            # We edit the purchase entity and save it in a variable for later use as a ForeignKey
            purchase = form.save()
            
            # Now we erase all products from the current purchase to then add the new ones.
            InventoryPurchase.objects.filter(purchase_id = purchase.id).delete()

            # Loop through the POST data to get the id of each N item in a dict of our own
            product_keys = {}
            product_count = 0
            for key in request.POST :
                # If input name matches, we store the id as a value in our dict
                if key.find("product_name_") != -1:
                    product_keys[product_count] = key.split("_")[2]
                    product_count += 1

            # Now we iterate our dictionary with the ID values to get each form field sent
            for id in product_keys.values():

                if request.POST.get('product_name_' + str(id)) is None:
                    break

                product = request.POST.__getitem__('product_name_' + str(id))
                quantity = request.POST.__getitem__('quantity_' + str(id))
                price = request.POST.__getitem__('price_' + str(id))

                # CHECK IF THE PRODUCT NAME IS A NUMBER IF IT IS A NUMBER, THEN IT IS A PRODUCT ID
                if product.isdigit():
                    # Link the product to the current Purchase
                    InventoryPurchase.objects.create(
                        inventory = Inventario.objects.get(id=product),
                        purchase = purchase,
                        price = price,
                        supplier = "",
                        quantity = quantity,
                        transaction_type = "storage",
                    )
                # IF IT IS NOT A NUMBER, THEN IT IS A PRODUCT NAME AND WE NEED TO CREATE A NEW PRODUCT
                else:
                    inventory_name = product

                    # Try to get the product with the same SKU
                    if Inventario.objects.filter(sku=request.POST.__getitem__('sku_' + str(id))).exists():
                    # If the product exists it return a error
                        msg = "One SKU already exits. Please enter a different SKU"
                        form.add_error(None, msg)

                        # send error messages in context
                        context = {'form': form}
                        
                        # Get the current id of the puchase

apps/examplePurchases/templates/examplePurchases/index.html
{% extends 'base.html' %} {% load static %}

{% block title %}
    Índice de compras
{% endblock %}



{% block css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/css/theme.bootstrap_4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
{% endblock %}



{% block content %}
    <!-- Start: Ludens - 1 Index Table with Search & Sort Filters -->
    <div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-sm-6 col-md-6">
                    <h3 class="text-dark mb-4">Compras</h3>
                </div>

                <div class="col-12 col-sm-6 col-md-6 text-end" style="margin-bottom: 30px;">
                    <a class="btn btn-primary" role="button" href="{% url 'examplePurchases:create' %}">
                        <i class="fa fa-plus"></i> &nbsp;Agregar producto
                    </a>
                </div>
            </div>

            <!-- Start: TableSorter -->
            <div class="card" id="TableSorterCard">
                
                <div class="card-header py-3">
                    <div class="row table-topper align-items-center">
                        <div class="col-12 col-sm-5 col-md-6 text-start" style="margin: 0px;padding: 5px 15px;">
                            <p class="m-0 fw-bold" style="color:#10312b">Lista de las compras</p>
                        </div>
                        

                        <form class="search-form w-100" method="get" id="avc_filters">
                            <div class="row">
                                <div class="col-md-12 bg-white" style="text-align: left;">
                                    <div class="row">
                                        {% for filter_name in filter.form %}
                                            <div class="col-sm-4 col-md-4 my-3">
                                                <label class="form-label" style="font-weight: bold;" for="{{ form.zone_name.id_for_label }}">{{ filter_name.label_tag }}</label>
                                                <div class="input-group">
                                                    {{ filter_name }}
                                                </div>
                                            </div>
                                        {% endfor %}
                                        <div class="text-end" style="margin: 0px;padding: 5px 15px;">

                                            <button class="btn btn-primary btn-sm my-1 mr-1" type="submit">Filtrar</button>

                                            <a href="{{request.path}}" class="btn btn-danger btn-sm reset my-1 mr-1" type="button">Borrar Filtros</a>
                                            
                                            <button class="btn btn-warning btn-sm my-1 mr-1" id="zoom_in" type="button" zoomclick="ChangeZoomLevel(-10);">
                                                <i class="fa fa-search-plus"></i>
                                            </button>
                
                                            <button class="btn btn-warning btn-sm my-1 mr-1" id="zoom_out" type="button" zoomclick="ChangeZoomLevel(-10);">
                                                <i class="fa fa-search-minus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table table-striped table tablesorter" id="ipi-table">
                                <thead class="thead-dark">
                                    <tr>
                                        <th class="text-center">Fecha</th>

                                        <th class="text-center">Gasto</th>

                                        <th class="text-center">Descripcion</th>

                                        <th class="text-center filter-false sorter-false">Acciones</th>
                                    </tr>
                                </thead>

                                <tbody class="text-center">
                                    {% for purchase in purchases %}
                                    <tr>
                                        <td>
                                            {{purchase.date}}
                                        </td>

                                        <td>
                                            {{purchase.total_price}}
                                        </td>

                                        <td>
                                            {{purchase.description}}
                                        </td>

                                        <td class="text-center align-middle" style="max-height: 60px;height: 60px;">
                                            <a class="btn btnMaterial btn-flat primary semicircle" role="button" href="{% url 'examplePurchases:show' purchase.id %}">
                                                <i class="far fa-eye"></i>
                                            </a>
                                            <a class="btn btnMaterial btn-flat success semicircle" role="button" href="{% url 'examplePurchases:edit' purchase.id %}">
                                                <i class="fas fa-pen"></i>
                                            </a>

                                            <a class="btn btnMaterial btn-flat accent btnNoBorders checkboxHover" role="button" style="margin-left: 5px;" data-bs-toggle="modal" onclick="destroy({{purchase.id}})" data-bs-target="#delete-modal" href="#">
                                                <i class="fas fa-trash btnNoBorders" style="color: #DC3545;"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End: Ludens - 1 Index Table with Search & Sort Filters -->

    <div class="container" style="margin-top: 25px;">
        <nav class="d-lg-flex justify-content-lg-center">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>

                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&lsaquo;</span>
                        </a>
                    </li>
                {% endif %}

                <li class="page-item">
                    <a class="page-link" >Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&rsaquo;</span>
                        </a>
                    </li>

                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Previous">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>


    <form id="deleteForm" method="post">
        {% csrf_token %}
        <div class="modal fade" role="dialog" tabindex="-1" id="delete-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" style="font-size: 20px;">Eliminar Producto</h4>

                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <div class="modal-body">
                        <p style="font-size: 18px;color: rgb(58,59,69);">
                            Si eliminas este elemento ya no podrás recuperarlo.
                        </p>
                    </div>

                    <div class="modal-footer">
                        <button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancelar</button>

                        <button class="btn btn-danger" type="button" onclick="formSubmit()">Eliminar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <a class="border rounded d-inline scroll-to-top" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
{% endblock %}



{% block js %}
    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/jquery.tablesorter.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-filter.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-storage.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
        {% for message in messages %}
            <script>
                let title = "";
                if("{{message.tags}}" === 'error'){
                    title = "¡Error!";
                }
                if ('{{message.tags}}' === 'success'){
                    title = "Éxito!";
                }
                if ("{{message.tags}}" === 'warning'){
                    title = "Advertencia!";
                }
                if ("{{message.tags}}" === 'info'){
                    title = "Información";
                }
    
                Swal.fire({
                    title: title,
                    text: '{{message}}',
                    type: '{{message.tags}}',
                    icon: '{{message.tags}}',
                    confirmButtonText: 'OK'
                });
    
            </script>
        {% endfor %}
    {% endif %}

    <!-- Delete Script -->
    <script>
        function destroy(id) {
            let url = "{% url 'examplePurchases:delete' 1 %}";
            url = url.replace('1', id);
            $("#deleteForm").attr('action', url);
        }
        function formSubmit() {
            $("#deleteForm").submit();
        }
    </script>
{% endblock %}