apps/history/urls.py
from django.urls import path
from . import views

app_name = 'history'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('users/', views.UserLogsView.as_view(), name='users'),
    path('inventories/', views.InventoriesLogsView.as_view(), name='inventories'),
    path('purchases/', views.PurchasesLogsView.as_view(), name='purchases'),
    path('recover-users/<int:pk>/', views.UserRollbackView.as_view(), name='recover-users'),
    path('recover-inventories/<int:pk>/', views.InventoriesRollbackView.as_view(), name='recover-inventories'),
    path('recover-purchases/<int:pk>/', views.PurchasesRollbackView.as_view(), name='recover-purchases'),
    # path('profile/', views.ProfileView.as_view(), name='profile'),
]

apps/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # path('', views.ViewPurchase.as_view(), name='index'),
    # path('profile/', views.ProfileView.as_view(), name='profile'),
]

djangoproject/urls.py
"""djangoproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.urls import include, path
from apps.users import views as users_views
from django.contrib.admin.views.decorators import staff_member_required


# from exampleApp.views import IndexExample

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('apps.dashboard.urls')),
    path('inventario/', include('apps.exampleInventario.urls')),
    path('compras/', include('apps.examplePurchases.urls')),
    path('log/', include('apps.history.urls')),
    path('animals/', include('apps.drfexampleapp.urls')),
    
    # User and Registration urls
    path('', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('profile/', users_views.ProfileView.as_view(), name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/login.html'), name='logout'),
    path('register/', users_views.RegisterView.as_view(), name='register'),
    path('register-admin/', staff_member_required(users_views.RegisterViewAdmin.as_view()), name='registerAdmin'),

    path('forgot-password/', users_views.forgot_password, name='forgot-password'),
    path('users/', include('apps.users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Remember that the last line regarding file/image uploads must be changed for production purposes: 
# https://docs.djangoproject.com/en/4.0/howto/static-files/deployment/

apps/history/models.py
from django.db import models

# Create your models here.

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from random import randrange
from simple_history.models import HistoricalRecords
from safedelete.models import SafeDeleteModel, SOFT_DELETE_CASCADE

def random_image_chooser():
    """This defines the default image for the user"""
    # images = [
    #     'profiles/generic/profile_happy.png',
    #     'profiles/generic/profile_kakashi.jpg',
    #     'profiles/generic/profile_whats.jpg',
    # ]
    # i = randrange(3)
    # return images[i]


class User(AbstractUser, SafeDeleteModel):
    _safedelete_policy = SOFT_DELETE_CASCADE
    image = models.ImageField(upload_to='profiles/', max_length=255, blank=True, null=True, default='profiles/generic/blank-profile-pic.png')
    city = models.CharField(max_length=255, blank=True, null=True)
    state = models.CharField(max_length=255, blank=True)
    country = models.CharField(max_length=255, blank=True)
    address = models.CharField(max_length=255, blank=True)
    dark_mode = models.BooleanField(default=False)
    history = HistoricalRecords()
    
    class Meta:
        db_table = 'users'
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['id']

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.safestring import mark_safe
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ValidationError
from django.core.validators import validate_email, RegexValidator
# from django.contrib.auth.models import User
from .models import User


class EditProfileForm(forms.ModelForm):

	password = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password','id':'password', 'placeholder': 'Password'}))
	password2 = forms.CharField(required=False, label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password', 'id': 'verifyPassword'}))
	class Meta:
		model = User

        # Define the fields that will be displayed on the form with their DB column names
		fields = [
			"first_name", 
			"last_name", 
			"email", 
			"password",
			"password2",
			"image", 
			"city", 
			"state",
			'username',		
			"country",
			'address',
			'image',
		]


        # Modify any labels here if required
		labels = {
			# mark_safe to prevent XSS attacks
			'image': mark_safe(''), # Clean the image label
			'email': mark_safe('<b>Email Address*</b>'),
			'username': mark_safe('<b>Username</b>'),
			'first_name': mark_safe('<b>First Name*</b>'),
			'last_name': mark_safe('<b>Last Name*</b>'),
			'country': mark_safe('<b>Country*</b>'),
			'state': mark_safe('<b>State*</b>'),
			'city': mark_safe('<b>City</b>'),
			'address': mark_safe('<b>Address</b>'),
		}
		

        # Modify the input attributes
		widgets = {
			'first_name': forms.TextInput(attrs={'class': 'form-control', 'name': 'first_name', 'placeholder': 'First Name', 'required': ''}),
			'last_name': forms.TextInput(attrs={'class': 'form-control', 'name': 'last_name', 'placeholder': 'Last Name', 'required': ''}),
			'email': forms.TextInput(attrs={'class': 'form-control', 'name': 'email','id':'email', 'placeholder': 'Email Address', 'required': ''}),
			'username': forms.TextInput(attrs={'class': 'form-control', 'name': 'username', 'placeholder': 'Username', 'required': ''}),
			'country': forms.Select(attrs={'class': 'form-select countries order-alpha limit-pop-1000000 presel-MX group-continents group-order-na', 'name': 'country', 'required': '', 'id': 'countryId'}),
			'state': forms.Select(attrs={'class': 'form-select states order-alpha', 'name': 'state', 'required': '', 'id': 'stateId'}),
			'city': forms.TextInput(attrs={'class': 'form-control', 'name': 'city', 'placeholder': 'City', 'id': 'cityId'}),
			'address': forms.TextInput(attrs={'class': 'form-control', 'name': 'address', 'placeholder': 'Address'}),
		}
  
		help_texts = {
			"username": ""
		}
  
	def clean_email(self):
		email = self.cleaned_data.get('email')
		user = self.instance
		if User.objects.filter(email=email).exists() and user.email != email:
			raise ValidationError('This email is already taken')
		return email

	def clean_username(self):
		username = self.cleaned_data.get('username')
		user = self.instance
		if User.objects.filter(username=username).exists() and user.username != username:
			raise ValidationError('This username is already taken')
		return username
  
	def __ini__(self, *args, **kwargs):
		super(EditProfileForm, self).__init__(*args, **kwargs)
  
		self.fields['password'].required = False
		self.fields['password2'].required = False
  
		self.fields['username'].help_text = ''

  
	

	def save(self, commit=True):
		user = super(EditProfileForm, self).save(commit=False)
		password = self.cleaned_data["password"]
		if password != '':
			user.set_password(self.cleaned_data['password'])
		else:
			actual_user = User.objects.get(id=user.id)
			user.password = actual_user.password
		if commit:
			user.save()
		return user




class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True, 
								widget=forms.TextInput(attrs={'placeholder': 'email', 'id':'email'}))

	username = forms.CharField(required=True, 
								widget=forms.TextInput(attrs={'placeholder': 'username'}))

	password1 = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'Password',
            'type': 'password',
            'minlength': 8,
			'id':'password'}), required=True, label="Password")

	password2 = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'Password',
            'type': 'password',
            'minlength': 8,
			'id':'verifyPassword'}), required=True, label="Verify password")

	first_name = forms.CharField(required=True, 
								widget=forms.TextInput(attrs={'placeholder': 'first name'}))

	last_name = forms.CharField(required=True, 
								widget=forms.TextInput(attrs={'placeholder': 'last name'}))



	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2", "first_name", "last_name")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

	def clean_username(self):
		username  = self.cleaned_data.get('username')
		if User.objects.filter(username=username).exists():
			raise ValidationError('This username is already taken')
		return username

	def clean_email(self):
		email  = self.cleaned_data.get('email')
		if User.objects.filter(email=email).exists():
			raise ValidationError('This email is already taken')
		return email
	
	def __init__(self, *args, **kwargs):
		super(NewUserForm, self).__init__(*args, **kwargs)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control form-control-user'

apps/history/views.py
from django.shortcuts import render, redirect

from django.views.generic import ListView, UpdateView, DeleteView, CreateView, TemplateView
from django.views import View
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin

from ..users.models import User
from ..examplePurchases.models import InventoryPurchase, Purchase
from ..exampleInventario.models import Inventario
# Create your views here.


class IndexView(PermissionRequiredMixin, TemplateView):
    permission_required = 'history.view_history'
    template_name = "history/logs.html"
    

# App 'Users'
class UserLogsView(PermissionRequiredMixin, ListView):
    permission_required = 'history.view_history'
    model = User
    template_name = "history/users.html"
    context_object_name = 'history'
    paginate_by = 20
    queryset = User.history.all()
    
    
class UserRollbackView(PermissionRequiredMixin, View):
    permission_required = 'history.change_history'
    model = User
    success_url = reverse_lazy('history:users')
    
    def post(self, request, pk, *args, **kwargs):
        history = self.model.history.get(pk=pk)
        history.save()
        return redirect(self.success_url)


# App 'Purchases'
class PurchasesLogsView(PermissionRequiredMixin, ListView):
    permission_required = 'history.view_history'
    model = Purchase
    template_name = "history/purchases.html"
    context_object_name = 'history'
    paginate_by = 20
    queryset = Purchase.history.all()
    
    
class PurchasesRollbackView(PermissionRequiredMixin, View):
    permission_required = 'history.change_history'
    model = Purchase
    success_url = reverse_lazy('history:purchases')
    
    def post(self, request, pk, *args, **kwargs):
        history = self.model.history.get(pk=pk)
        history.save()
        return redirect(self.success_url)


# App 'Inventario'
class InventoriesLogsView(PermissionRequiredMixin, ListView):
    permission_required = 'history.view_history'
    model = Inventario
    template_name = "history/inventories.html"
    context_object_name = 'history'
    paginate_by = 20
    queryset = Purchase.history.all()
    
    
class InventoriesRollbackView(PermissionRequiredMixin, View):
    permission_required = 'history.change_history'
    model = Inventario
    success_url = reverse_lazy('history:inventories')
    
    def post(self, request, pk, *args, **kwargs):
        history = self.model.history.get(pk=pk)
        history.save()
        return redirect(self.success_url)

apps/users/views.py
from django.shortcuts import  render, redirect
from django.contrib.auth import login
from django.views import generic
from django.urls import reverse_lazy
from django.db import transaction
from django.contrib.auth.mixins import LoginRequiredMixin


from .models import User
from .forms import NewUserForm, EditProfileForm

class RegisterView(generic.FormView):
    template_name = 'registration/register.html'
    form_class = NewUserForm
    success_url = reverse_lazy('login')

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        form = NewUserForm(data=request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
            
        else:
            context = {'form': form}
            return render(request, self.template_name, context)

        return redirect(self.get_success_url())



# Forgot Password (TODO)
def forgot_password(request):
    context = {}
    return render(request=request, template_name="registration/forgot-password.html")


# Profile
class ProfileView(LoginRequiredMixin, generic.UpdateView):
    model = User
    template_name = 'users/profile.html'
    form_class = EditProfileForm
    success_url = reverse_lazy('profile') # Redirect to index after 

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        return super(ProfileView, self).post(request, *args, **kwargs)
    
    def get_object(self, **kwargs):
        return self.request.user





class RegisterViewAdmin(generic.FormView):
    template_name = 'registration/register.html'
    form_class = NewUserForm
    success_url = reverse_lazy('login')

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        form = NewUserForm(data=request.POST)

        if form.is_valid():
            user = form.save()
            # login(request, user)
            return redirect('/')
            
        else:
            context = {'form': form}
            return render(request, self.template_name, context)

        return redirect(self.get_success_url())

apps/history/templates/history/inventories.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    User logs
{% endblock %}
{% block css %}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/css/theme.bootstrap_4.min.css"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"/>
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h3 class="text-dark mb-4">Inventory History Logs</h3>
            </div>
            <div class="col text-end">
                <button class="btn btn-danger btn-sm reset" type="button" style="margin: 2px;border-radius: 20px;">Delete Filters</button>
                <button class="btn btn-warning btn-sm" id="zoom_in" type="button" zoomclick="ChangeZoomLevel(-10);" style="margin: 2px;border-radius: 20px;">
                    <i class="fa fa-search-plus"></i>
                </button>
                <button class="btn btn-warning btn-sm" id="zoom_out" type="button" zoomclick="ChangeZoomLevel(-10);" style="margin: 2px;border-radius: 20px;">
                    <i class="fa fa-search-minus"></i>
                </button>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="table-responsive shadow" style="border-radius: 20px;border-style: none;">
            <table class="table table-striped table-borderless table tablesorter" id="ipi-table">
                <thead class="thead-dark">
                    <tr>
                        <th class="text-center">Date</th>
                        <th class="text-center">Issued by</th>
                        <th class="text-center">Name</th>
                        <th class="text-center filter-false sorter-false">Type</th>
                        <th class="text-center">Reason</th>
                        <th class="text-center filter-false sorter-false">Actions</th>
                    </tr>
                </thead>

                <tbody class="text-center">
                    {% for log in history %}
                        <tr>
                            <td>{{log.history_date}}</td>

                            <td>{% if log.history_user %} {{log.history_user}} {%else%} N/A {%endif%}</td>

                            <td>{{log.nombre}}</td>

                            <td>
                                {% if log.history_type == '+' %}
                                    <i title="Created" class="fas fa-plus-circle fs-5 text-success"></i>
                                {% elif log.history_type == '~' %}
                                    <i title="Modified" class="fas fa-pen-square fs-5 text-primary"></i>
                                {% elif log.history_type == '-' %}
                                    <i title="Deleted" class="fas fa-minus-circle fs-5 text-danger"></i>
                                {% endif %}
                            </td>

                            <td>{% if log.histoy_change_reason %} {{ log.histoy_change_reason }} {%else%} N/A {%endif%}</td>

                            <td class="text-center align-middle" style="max-height: 60px;height: 60px;">
                                <a class="btn btnMaterial btn-flat primary semicircle" role="button"
                                    id="Bnt_hover" href="#">
                                    <i title="Change details" class="far fa-eye"></i>
                                </a>

                                <a class="btn btnMaterial btn-flat accent btnNoBorders checkboxHover"
                                    role="button" onclick="destroy({{log.id}})" id="Bnt_hover"
                                    data-bs-toggle="modal" data-bs-target="#recover-modal" href="#">
                                    <i title="Revert change" class="fas fa-sync-alt btnNoBorders" style="color: #DC3545;"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <form id="recoverForm" method="post">
        {% csrf_token %}
        <div class="modal fade" role="dialog" tabindex="-1" id="recover-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" style="font-size: 20px;">Recover point in time</h4>

                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <div class="modal-body">
                        <p style="font-size: 18px;color: rgb(58,59,69);">
                            This is a destructive action.
                        </p>
                    </div>

                    <div class="modal-footer">
                        <button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancel</button>

                        <button class="btn btn-danger" type="button" onclick="formSubmit()">Revert</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    
    <!-- End: Ludens - 1 Index Table with Search & Sort Filters -->
    <!-- Pagination -->
    <div class="container" style="margin-top: 25px">
        <nav class="d-lg-flex justify-content-lg-center">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link"
                           href="?page={{ page_obj.previous_page_number }}"
                           aria-label="Previous">
                            <span aria-hidden="true">&lsaquo;</span>
                        </a>
                    </li>
                {% endif %}
                <li class="page-item">
                <a class="page-link" s>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a
                >
            </li>
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ page_obj.next_page_number }}"
                       aria-label="Previous">
                        <span aria-hidden="true">&rsaquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ page_obj.paginator.num_pages }}"
                       aria-label="Previous">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}


{% block js %}
    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/jquery.tablesorter.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-filter.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-storage.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

    <!-- Delete POST Script -->
    <script>
        function destroy(id) {
            let url = "{% url 'history:recover-inventories' 1 %}".replace('1', id);
            $("#recoverForm").attr('action', url);
        }
        function formSubmit() {
            $("#recoverForm").submit();
        }
    </script>
{% endblock %}

apps/history/templates/history/purchases.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    User logs
{% endblock %}
{% block css %}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/css/theme.bootstrap_4.min.css"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"/>
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h3 class="text-dark mb-4">Purchases History Logs</h3>
            </div>
            <div class="col text-end">
                <button class="btn btn-danger btn-sm reset" type="button" style="margin: 2px;border-radius: 20px;">Delete Filters</button>
                <button class="btn btn-warning btn-sm" id="zoom_in" type="button" zoomclick="ChangeZoomLevel(-10);" style="margin: 2px;border-radius: 20px;">
                    <i class="fa fa-search-plus"></i>
                </button>
                <button class="btn btn-warning btn-sm" id="zoom_out" type="button" zoomclick="ChangeZoomLevel(-10);" style="margin: 2px;border-radius: 20px;">
                    <i class="fa fa-search-minus"></i>
                </button>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="table-responsive shadow" style="border-radius: 20px;border-style: none;">
            <table class="table table-striped table-borderless table tablesorter" id="ipi-table">
                <thead class="thead-dark">
                    <tr>
                        <th class="text-center">Date</th>
                        <th class="text-center">Issued by</th>
                        <th class="text-center">Purchase ID</th>
                        <th class="text-center filter-false sorter-false">Type</th>
                        <th class="text-center">Reason</th>
                        <th class="text-center filter-false sorter-false">Actions</th>
                    </tr>
                </thead>

                <tbody class="text-center">
                    {% for log in history %}
                        <tr>
                            <td>{{log.history_date}}</td>

                            <td>{% if log.history_user %} {{log.history_user}} {%else%} N/A {%endif%}</td>

                            <td>{{log.id}}</td>

                            <td>
                                {% if log.history_type == '+' %}
                                    <i title="Created" class="fas fa-plus-circle fs-5 text-success"></i>
                                {% elif log.history_type == '~' %}
                                    <i title="Modified" class="fas fa-pen-square fs-5 text-primary"></i>
                                {% elif log.history_type == '-' %}
                                    <i title="Deleted" class="fas fa-minus-circle fs-5 text-danger"></i>
                                {% endif %}
                            </td>

                            <td>{% if log.histoy_change_reason %} {{ log.histoy_change_reason }} {%else%} N/A {%endif%}</td>

                            <td class="text-center align-middle" style="max-height: 60px;height: 60px;">
                                <a class="btn btnMaterial btn-flat primary semicircle" role="button"
                                    id="Bnt_hover" href="#">
                                    <i title="Change details" class="far fa-eye"></i>
                                </a>

                                <a class="btn btnMaterial btn-flat accent btnNoBorders checkboxHover"
                                    role="button" onclick="destroy({{log.id}})" id="Bnt_hover"
                                    data-bs-toggle="modal" data-bs-target="#recover-modal" href="#">
                                    <i title="Revert change" class="fas fa-sync-alt btnNoBorders" style="color: #DC3545;"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <form id="recoverForm" method="post">
        {% csrf_token %}
        <div class="modal fade" role="dialog" tabindex="-1" id="recover-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" style="font-size: 20px;">Recover point in time</h4>

                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <div class="modal-body">
                        <p style="font-size: 18px;color: rgb(58,59,69);">
                            This is a destructive action.
                        </p>
                    </div>

                    <div class="modal-footer">
                        <button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancel</button>

                        <button class="btn btn-danger" type="button" onclick="formSubmit()">Revert</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    
    <!-- End: Ludens - 1 Index Table with Search & Sort Filters -->
    <!-- Pagination -->
    <div class="container" style="margin-top: 25px">
        <nav class="d-lg-flex justify-content-lg-center">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link"
                           href="?page={{ page_obj.previous_page_number }}"
                           aria-label="Previous">
                            <span aria-hidden="true">&lsaquo;</span>
                        </a>
                    </li>
                {% endif %}
                <li class="page-item">
                <a class="page-link" s>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a
                >
            </li>
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ page_obj.next_page_number }}"
                       aria-label="Previous">
                        <span aria-hidden="true">&rsaquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ page_obj.paginator.num_pages }}"
                       aria-label="Previous">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}


{% block js %}
    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/jquery.tablesorter.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-filter.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-storage.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

    <!-- Delete POST Script -->
    <script>
        function destroy(id) {
            let url = "{% url 'history:recover-purchases' 1 %}".replace('1', id);
            $("#recoverForm").attr('action', url);
        }
        function formSubmit() {
            $("#recoverForm").submit();
        }
    </script>
{% endblock %}