apps/exampleInventario/urls.py
from django.urls import path
from . import views

app_name = 'exampleInventario'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create/', views.Create.as_view(), name='create'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete')
]

djangoproject/urls.py
"""djangoproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.urls import include, path
from apps.users import views as users_views
from django.contrib.admin.views.decorators import staff_member_required


# from exampleApp.views import IndexExample

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('apps.dashboard.urls')),
    path('inventario/', include('apps.exampleInventario.urls')),
    path('compras/', include('apps.examplePurchases.urls')),
    path('log/', include('apps.history.urls')),
    path('animals/', include('apps.drfexampleapp.urls')),
    
    # User and Registration urls
    path('', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('profile/', users_views.ProfileView.as_view(), name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/login.html'), name='logout'),
    path('register/', users_views.RegisterView.as_view(), name='register'),
    path('register-admin/', staff_member_required(users_views.RegisterViewAdmin.as_view()), name='registerAdmin'),

    path('forgot-password/', users_views.forgot_password, name='forgot-password'),
    path('users/', include('apps.users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Remember that the last line regarding file/image uploads must be changed for production purposes: 
# https://docs.djangoproject.com/en/4.0/howto/static-files/deployment/

apps/exampleInventario/models.py
from django.db import models
from simple_history.models import HistoricalRecords
from safedelete.models import SafeDeleteModel, SOFT_DELETE_CASCADE

class Inventario(SafeDeleteModel):
    _safedelete_policy = SOFT_DELETE_CASCADE
    nombre = models.CharField(max_length=50)
    sku = models.CharField(max_length=50, unique=True)
    history = HistoricalRecords()
    
    class Meta:
        verbose_name = "Inventario"
        verbose_name_plural = "Inventarios"
        db_table = "inventario"
        ordering = ['-id']      # Orders by Id ("-" means descending)




apps/exampleInventario/forms.py
from .models import Inventario
from django import forms


#crear formulario
class InventarioForm(forms.ModelForm):

    def clean_sku(self):
        # if the sku is already in the database, raise an error
        sku = self.cleaned_data['sku']
        if Inventario.objects.filter(sku=sku).exists() or Inventario.deleted_objects.filter(sku=sku).exists():
            raise forms.ValidationError("One SKU already exits. Please enter a different SKU")
        return sku

    class Meta:
        model = Inventario
        fields = '__all__' # You can change this for the field's name
        exclude = ['is_deleted' , 'deleted_at']
        
        widgets = {
            'nombre': forms.TextInput(attrs={'placeholder':'Nombre de producto'}),
            'sku': forms.TextInput(attrs={'placeholder':'Identificador del producto'}),
        }

apps/exampleInventario/views.py
from re import template
from django.shortcuts import redirect, render
from django.db import models
from .models import Inventario
from django.views.generic import ListView, UpdateView, DeleteView, CreateView
from django_filters.views import FilterView
from django.urls import reverse_lazy
from .forms import InventarioForm
from .filters import InventarioFilter
from django.db import transaction


class Index(FilterView):
    model = Inventario
    template_name = "exampleInventario/index.html"
    context_object_name = 'inventario'
    paginate_by = 20
    filterset_class = InventarioFilter

    
class Create(CreateView):
    model = Inventario
    template_name = "exampleInventario/create.html"
    form_class = InventarioForm
    success_url = reverse_lazy('exampleInventario:index')

class Edit(UpdateView):
    model = Inventario
    template_name = "exampleInventario/edit.html"
    form_class = InventarioForm
    success_url = reverse_lazy('exampleInventario:index') 

class Delete(DeleteView):
    model = Inventario
    success_url = reverse_lazy('exampleInventario:index')

apps/exampleInventario/templates/exampleInventario/create.html
{% extends 'base.html' %} {% load static %}

{% block title %}
    Alta de Producto en Inventario
{% endblock %}



{% block css %}
    
{% endblock %}



{% block content %} 
    {% load crispy_forms_tags %}

    <section class="clean-block clean-form dark">
        <div class="container">
            <div class="row" style="margin-right: 0px;margin-left: 0px;">
                <div class="col-md-12" style="margin-bottom: 25px;padding-left: 5%;font-size: 21px;margin-top: 0px;">
                    <a class="anone" href="{% url 'exampleInventario:index' %}">
                        <i class="fas fa-long-arrow-alt-left"></i>
                        <span>&nbsp;Volver</span>
                    </a>
                </div>
            </div>

            <div class="block-heading" style="padding-top: 0px;">
                <h2 class="text-primary">
                    Añadir producto

                    <br>
                </h2>

                <p>
                    Los que tengan el * son datos que se tienen que rellenar obligatoriamente
                </p>
            </div>

            <form style="max-width: 700px;" role="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {% if form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ form.non_field_errors }}</strong>
                        </div>
                {% endif %}

                {% for  field in form %}
                
                <div class="form-group mb-3">
                    <strong>{{ field|as_crispy_field }}</strong>
                </div>

                {% endfor %}
                
                <hr style="margin-top: 30px;margin-bottom: 10px;">

                <div class="form-group mb-3">
                    <button class="btn btn-primary d-block w-100" id="submitButton" type="submit">
                        <i class="fas fa-save"></i>
                        &nbsp;Guardar
                    </button>

                    <a class="btn btn-danger d-block w-100" role="button" href="{% url 'exampleInventario:index' %}" style="margin-top: 15px;">
                        <i class="fas fa-arrow-left"></i> &nbsp;Cancelar
                    </a>
                </div>
            </form>
        </div>
    </section>
{% endblock %}



{% block js %}
    
{% endblock %}

apps/exampleInventario/templates/exampleInventario/edit.html
{% extends 'base.html' %} {% load static %}

{% block title %}
    Edición de Producto en Inventario
{% endblock %}



{% block css %}

{% endblock %}



{% block content %}
    {% load crispy_forms_tags %}

    <section class="clean-block clean-form dark">
        <div class="container">
            <div class="row" style="margin-right: 0px;margin-left: 0px;">
                <div class="col-md-12" style="margin-bottom: 25px;padding-left: 5%;font-size: 21px;margin-top: 0px;">
                    <a class="anone" href="{% url 'exampleInventario:index' %}">
                        <i class="fas fa-long-arrow-alt-left"></i>
                        <span>&nbsp;Volver</span>
                    </a>
                </div>
            </div>

            <div class="block-heading" style="padding-top: 0px;">
                <h2 class="text-primary">
                    Añadir producto

                    <br>
                </h2>

                <p>
                    Los que tengan el * son datos que se tienen que rellenar obligatoriamente
                </p>
            </div>

            <form style="max-width: 700px;" role="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                
                {% if form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ form.non_field_errors }}</strong>
                        </div>
                {% endif %}

                {% for  field in form %}
                
                <div class="form-group mb-3">
                    <strong>{{ field|as_crispy_field }}</strong>
                </div>

                {% endfor %}

                <hr style="margin-top: 30px;margin-bottom: 10px;">

                <div class="form-group mb-3">
                    <button class="btn btn-primary d-block w-100" id="submitButton" type="submit">
                        <i class="fas fa-save"></i>
                        &nbsp;Guardar
                    </button>

                    <a class="btn btn-danger d-block w-100" role="button" href="{% url 'exampleInventario:index' %}" style="margin-top: 15px;">
                        <i class="fas fa-arrow-left"></i> &nbsp;Cancelar
                    </a>
                </div>
            </form>
        </div>
    </section>
{% endblock %}



{% block js %}
    
{% endblock %}

apps/exampleInventario/templates/exampleInventario/index.html
{% extends 'base.html' %} {% load static %} 

{% block title %}
    Índice de Inventario
{% endblock %}



{% block css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/css/theme.bootstrap_4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
{% endblock %}



{% block content %}
    <!-- Start: Ludens - 1 Index Table with Search & Sort Filters -->
    <div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-sm-6 col-md-6">
                    <h3 class="text-dark mb-4">Inventario</h3>
                </div>

                <div class="col-12 col-sm-6 col-md-6 text-end" style="margin-bottom: 30px;">
                    <a class="btn btn-primary" role="button" href="{% url 'exampleInventario:create' %}">
                        <i class="fa fa-plus"></i> &nbsp;Agregar producto
                    </a>
                </div>
            </div>

            <div class="card" id="TableSorterCard">

                <div class="card-header py-3">
                    <div class="row table-topper align-items-center">
                        <div class="col-12 col-sm-5 col-md-6 text-start" style="margin: 0px;padding: 5px 15px;">
                            <p class="m-0 fw-bold" style="color:#10312b">Lista del inventario</p>
                        </div>
                        

                        <form class="search-form w-100" method="get" id="avc_filters">
                            <div class="row">
                                <div class="col-md-12 bg-white" style="text-align: left;">
                                    <div class="row">
                                        {% for filter_name in filter.form %}
                                            <div class="col-sm-3 col-md-3 my-3">
                                                <label class="form-label" style="font-weight: bold;" for="{{ form.zone_name.id_for_label }}">{{ filter_name.label_tag }}</label>
                                                <div class="input-group">
                                                    {{ filter_name }}
                                                </div>
                                            </div>
                                        {% endfor %}
                                        <div class="text-end" style="margin: 0px;padding: 5px 15px;">

                                            <button class="btn btn-primary btn-sm my-1 mr-1" type="submit">Filtrar</button>

                                            <a href="{{request.path}}" class="btn btn-danger btn-sm reset my-1 mr-1" type="button">Borrar Filtros</a>
                                            
                                            <button class="btn btn-warning btn-sm my-1 mr-1" id="zoom_in" type="button" zoomclick="ChangeZoomLevel(-10);">
                                                <i class="fa fa-search-plus"></i>
                                            </button>
                
                                            <button class="btn btn-warning btn-sm my-1 mr-1" id="zoom_out" type="button" zoomclick="ChangeZoomLevel(-10);">
                                                <i class="fa fa-search-minus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table table-striped table tablesorter" id="ipi-table">
                                <thead class="thead-dark">
                                    <tr>
                                        <th class="text-center">Nombre</th>

                                        <th class="text-center">sku</th>

                                        <th class="text-center filter-false sorter-false">Acciones</th>
                                    </tr>
                                </thead>

                                <tbody class="text-center">
                                    {% for producto in inventario %}
                                    <tr>
                                        <td>
                                            {{producto.nombre}}
                                        </td>

                                        <td>
                                            {{producto.sku}}
                                        </td>

                                        <td class="text-center align-middle" style="max-height: 60px;height: 60px;">
                                            <a class="btn btnMaterial btn-flat success semicircle" role="button" href="{% url 'exampleInventario:edit' producto.id %}">
                                                <i class="fas fa-pen"></i>
                                            </a>

                                            <a class="btn btnMaterial btn-flat accent btnNoBorders checkboxHover" role="button" style="margin-left: 5px;" data-bs-toggle="modal" onclick="destroy({{producto.id}})" data-bs-target="#delete-modal" href="#">
                                                <i class="fas fa-trash btnNoBorders" style="color: #DC3545;"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End: TableSorter -->
        </div>
    </div>
    <!-- End: Ludens - 1 Index Table with Search & Sort Filters -->


    <!-- Pagination -->
    <div class="container" style="margin-top: 25px;">
        <nav class="d-lg-flex justify-content-lg-center">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>

                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&lsaquo;</span>
                    </a>
                </li>
                {% endif %}

                <li class="page-item">
                    <a class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
                </li>

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&rsaquo;</span>
                    </a>
                </li>

                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Previous">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>

    <!-- Delete modal -->
    <form id="deleteForm" method="post">
        {% csrf_token %}
        <div class="modal fade" role="dialog" tabindex="-1" id="delete-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" style="font-size: 20px;">Eliminar Producto</h4>

                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <div class="modal-body">
                        <p style="font-size: 18px;color: rgb(58,59,69);">
                            Si eliminas este elemento ya no podrás recuperarlo.
                        </p>
                    </div>

                    <div class="modal-footer">
                        <button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancelar</button>

                        <button class="btn btn-danger" type="button" onclick="formSubmit()">Eliminar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    
    <a class="border rounded d-inline scroll-to-top" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
{% endblock %}



{% block js %}
    <!-- Table's core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/jquery.tablesorter.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-filter.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-storage.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
        {% for message in messages %}
            <script>
                let title = "";
                if("{{message.tags}}" === 'error'){
                    title = "¡Error!";
                }
                if ('{{message.tags}}' === 'success'){
                    title = "Éxito!";
                }
                if ("{{message.tags}}" === 'warning'){
                    title = "Advertencia!";
                }
                if ("{{message.tags}}" === 'info'){
                    title = "Información";
                }
    
                Swal.fire({
                    title: title,
                    text: '{{message}}',
                    type: '{{message.tags}}',
                    icon: '{{message.tags}}',
                    confirmButtonText: 'OK'
                });
    
            </script>
        {% endfor %}
    {% endif %}

    <!-- Delete Script -->
    <script>
        function destroy(id) {
            let url = "{% url 'exampleInventario:delete' 1 %}";
            url = url.replace('1', id);
            $("#deleteForm").attr('action', url);
        }
        function formSubmit() {
            $("#deleteForm").submit();
        }

    </script>
{% endblock %}